services:
  gitbucket:
    image: gitbucket/gitbucket:latest
    container_name: gitbucket
    ports:
      - "9666:8080"
      - "29418:29418" # Optional: SSH access
    volumes:
      - gitbucket_data:/gitbucket
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m

volumes:
  gitbucket_data:
