services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 32769:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkinsdata:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkinsdata:
