services:
  xe:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle
    network_mode: host
    environment:
      - ORACLE_PWD=root
    volumes:
      - data:/opt/oracle/oradata

volumes:
  data:
